### instalar a extenção Rest client no vscode

###
POST http://127.0.0.1:8000/api/v1/interesses HTTP/1.1
content-type: application/json
Authorization: Token dde9b45a66c3b8df195d868c6a4401408aa4b644

{
  "origem": 1,
  "destino": 2,
  "aceito": false
}

###
POST http://127.0.0.1:8000/api/v1/interesses HTTP/1.1
content-type: application/json
Authorization: Token 5c9e43fc7f45a38f9b383100b1d16ae1d5922050

{
  "origem": 2,
  "destino": 1,
  "aceito": false
}

###
POST http://127.0.0.1:8000/api/v1/interesses HTTP/1.1
content-type: application/json
Authorization: Token 93b5da54a13a750d4bc648abb054e7956156b827

{
  "origem": 3,
  "destino": 1,
  "aceito": false
}

### aceitar interesse
PUT http://127.0.0.1:8000/api/v1/aceitar-interesse/4 HTTP/1.1
content-type: application/json
Authorization: Token dde9b45a66c3b8df195d868c6a4401408aa4b644
{
  "origem": 2,
  "destino": 1,
  "aceito": true
}


###
GET http://127.0.0.1:8000/api/v1/interesses-pendentes HTTP/1.1
content-type: application/json
Authorization: Token dde9b45a66c3b8df195d868c6a4401408aa4b644

###
GET http://127.0.0.1:8000/api/v1/interesses-confirmados HTTP/1.1
content-type: application/json
Authorization: Token dde9b45a66c3b8df195d868c6a4401408aa4b644
