### instalar a extenção Rest client no vscode

### Dados do login
POST http://127.0.0.1:8000/api/v1/login HTTP/1.1
content-type: application/json

{
  "username": "jonatas",
  "password": "linux"
}

###
POST http://127.0.0.1:8000/api/v1/login HTTP/1.1
content-type: application/json

{
    "username": "Melo",
    "password": "Linuxlinux"
}

###
POST http://127.0.0.1:8000/api/v1/login HTTP/1.1
content-type: application/json

{
    "username": "Silva",
    "password": "Linuxlinux"
}


###
POST http://127.0.0.1:8000/api/v1/interesses HTTP/1.1
content-type: application/json
Authorization: Token dde9b45a66c3b8df195d868c6a4401408aa4b644

{
  "origem": 1,
  "destino": 2,
  "aceito": false
}
